version: "3"
services:
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wppassword
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword 
    volumes:
      - mysql:/var/lib/mysql 

  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    restart: always
    ports:
      - "81:80"
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./:/var/www/html
      - ./apache.conf:/etc/apache2/conf-enabled/apache.conf:ro

volumes:
  mysql: {}